#!/bin/bash

git pull

CURL_EXISTS=`which curl`

if [ -d ${CURL_EXISTS} ]; then
    echo "[i] Installing curl..."
    sudo apt-get --assume-yes install curl
fi

PATH="$PATH"

echo "[i] Check npm version"
sudo npm install npm@latest -g

echo "[i] Installing homebridge plugins..."
npm run homebridge-install

if [ ! -d /usr/local/lib/node_modules/pm2 ]; then
    echo "[i] Installing node process manager..."
    sudo npm install -g pm2
fi

echo "[i] Installing dependancies for freebox home server"
npm install

echo "[i] Starting services"
pm2
# first, start homebridge to setup the .homebridge env
# then, start the server
pm2 start src/index.js
pm2 save
pm2 startup
